networks:
  proxy_net:
    external: true
  db_net:
    external: true

services:
  postgres:
    image: postgres:16-alpine
    container_name: global-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${BASE_DIR}/02-database/init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/library/redis:alpine
    container_name: global-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - db_net

volumes:
  postgres_data:
